import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";
import { Phone, Package, Users, MapPin, Truck as TruckIcon, Calendar, Home as HomeIcon } from "lucide-react";
import Header from "@/components/layout/Header";
import { Link } from "react-router-dom";

interface Booking {
  id: string;
  tracking_id: string;
  booking_type: string;
  pickup_location: string;
  delivery_location: string;
  status: string;
  created_at: string;
  customer_id: string;
  driver_id: string | null;
  vehicle_id: string | null;
  passenger_count?: number;
  goods_type?: string;
  special_instructions?: string;
}

interface Driver {
  id: string;
  full_name: string;
  user_id: string;
}

interface Vehicle {
  id: string;
  vehicle_type: string;
  license_plate: string;
  capacity: number;
  is_available: boolean;
  driver_id: string | null;
}

interface Customer {
  id: string;
  full_name: string;
  phone: string;
  user_id: string;
}

const AssistantDashboard = () => {
  const navigate = useNavigate();
  const { profile, user, loading } = useAuth();
  const { toast } = useToast();
  const [bookings, setBookings] = useState<Booking[]>([]);
  const [drivers, setDrivers] = useState<Driver[]>([]);
  const [vehicles, setVehicles] = useState<Vehicle[]>([]);
  const [customers, setCustomers] = useState<Customer[]>([]);
  const [dataLoading, setDataLoading] = useState(true);

  // Create booking form state
  const [newBooking, setNewBooking] = useState({
    customer_id: "",
    booking_type: "passenger",
    pickup_location: "",
    delivery_location: "",
    passenger_count: 1,
    goods_type: "",
    special_instructions: "",
  });

  useEffect(() => {
    if (loading) return;
    if (!user) {
      navigate("/auth");
      return;
    }
    if (profile?.role !== "assistant") {
      navigate("/");
      return;
    }

    fetchAllData();
  }, [loading, user, profile, navigate]);

  const fetchAllData = async () => {
    try {
      await Promise.all([
        fetchBookings(),
        fetchDrivers(),
        fetchVehicles(),
        fetchCustomers(),
      ]);
    } finally {
      setDataLoading(false);
    }
  };

  const fetchBookings = async () => {
    const { data, error } = await supabase
      .from("bookings")
      .select("*")
      .order("created_at", { ascending: false });

    if (error) {
      console.error("Error fetching bookings:", error);
      toast({
        title: "Error",
        description: "Failed to load bookings",
        variant: "destructive",
      });
    } else {
      setBookings(data || []);
    }
  };

  const fetchDrivers = async () => {
    const { data, error } = await supabase
      .from("profiles")
      .select("id, full_name, user_id")
      .eq("role", "driver");

    if (error) {
      console.error("Error fetching drivers:", error);
    } else {
      setDrivers(data || []);
    }
  };

  const fetchVehicles = async () => {
    const { data, error } = await supabase
      .from("vehicles")
      .select("*")
      .eq("is_available", true);

    if (error) {
      console.error("Error fetching vehicles:", error);
    } else {
      setVehicles(data || []);
    }
  };

  const fetchCustomers = async () => {
    const { data, error } = await supabase
      .from("profiles")
      .select("id, full_name, phone, user_id")
      .eq("role", "customer");

    if (error) {
      console.error("Error fetching customers:", error);
    } else {
      setCustomers(data || []);
    }
  };

  const handleCreateBooking = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!newBooking.customer_id || !newBooking.pickup_location || !newBooking.delivery_location) {
      toast({
        title: "Error",
        description: "Please fill in all required fields",
        variant: "destructive",
      });
      return;
    }

    const { error } = await supabase.from("bookings").insert([
      {
        customer_id: newBooking.customer_id,
        booking_type: newBooking.booking_type as "passenger" | "goods",
        pickup_location: newBooking.pickup_location,
        delivery_location: newBooking.delivery_location,
        tracking_id: "", // Will be auto-generated by trigger
        passenger_count: newBooking.booking_type === "passenger" ? newBooking.passenger_count : null,
        goods_type: newBooking.booking_type === "goods" ? (newBooking.goods_type as "parcel" | "bulk" | "corporate" | null) : null,
        special_instructions: newBooking.special_instructions,
      },
    ]);

    if (error) {
      toast({
        title: "Error",
        description: error.message,
        variant: "destructive",
      });
    } else {
      toast({
        title: "Success",
        description: "Booking created successfully",
      });
      setNewBooking({
        customer_id: "",
        booking_type: "passenger",
        pickup_location: "",
        delivery_location: "",
        passenger_count: 1,
        goods_type: "",
        special_instructions: "",
      });
      fetchBookings();
    }
  };

  const handleAssignDriver = async (bookingId: string, driverId: string, vehicleId: string) => {
    const { error } = await supabase
      .from("bookings")
      .update({ driver_id: driverId, vehicle_id: vehicleId })
      .eq("id", bookingId);

    if (error) {
      toast({
        title: "Error",
        description: error.message,
        variant: "destructive",
      });
    } else {
      toast({
        title: "Success",
        description: "Driver assigned successfully",
      });
      fetchBookings();
    }
  };

  const handleUpdateStatus = async (bookingId: string, newStatus: string) => {
    const { error } = await supabase
      .from("bookings")
      .update({ status: newStatus as "pending" | "dispatched" | "delivered" | "received" })
      .eq("id", bookingId);

    if (error) {
      toast({
        title: "Error",
        description: error.message,
        variant: "destructive",
      });
    } else {
      // Send email notification
      try {
        await supabase.functions.invoke('send-booking-notification', {
          body: { bookingId, newStatus },
        });
      } catch (emailError) {
        console.error('Failed to send email notification:', emailError);
      }

      toast({
        title: "Success",
        description: "Status updated successfully",
      });
      fetchBookings();
    }
  };

  if (loading || !user) {
    return null;
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-background via-background to-primary/5">
      <Header />
      <div className="container mx-auto px-4 py-8">
        <div className="mb-8 flex justify-between items-start">
          <div>
            <h1 className="text-4xl font-bold mb-2 text-white">Assistant Dashboard</h1>
            <p className="text-slate-400">Create bookings and manage assignments</p>
          </div>
          <Button asChild variant="outline" className="border-white/10 bg-white/5 hover:bg-white/10 text-white gap-2">
            <Link to="/">
              <HomeIcon className="h-4 w-4" />
              Back to Home
            </Link>
          </Button>
        </div>

        <div className="grid gap-6 md:grid-cols-4 mb-8">
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Total Bookings</CardTitle>
              <Package className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{bookings.length}</div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Pending</CardTitle>
              <Calendar className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">
                {bookings.filter((b) => b.status === "pending").length}
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Available Drivers</CardTitle>
              <Users className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{drivers.length}</div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Available Vehicles</CardTitle>
              <TruckIcon className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{vehicles.length}</div>
            </CardContent>
          </Card>
        </div>

        <div className="grid gap-6 md:grid-cols-2">
          {/* Create Booking Form */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Phone className="h-5 w-5" />
                Create Booking (Phone Order)
              </CardTitle>
              <CardDescription>Create a booking on behalf of a customer</CardDescription>
            </CardHeader>
            <CardContent>
              <form onSubmit={handleCreateBooking} className="space-y-4">
                <div>
                  <Label htmlFor="customer">Customer</Label>
                  <Select
                    value={newBooking.customer_id}
                    onValueChange={(value) =>
                      setNewBooking({ ...newBooking, customer_id: value })
                    }
                  >
                    <SelectTrigger>
                      <SelectValue placeholder="Select customer" />
                    </SelectTrigger>
                    <SelectContent>
                      {customers.map((customer) => (
                        <SelectItem key={customer.id} value={customer.id}>
                          {customer.full_name} - {customer.phone}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div>
                  <Label htmlFor="booking_type">Service Type</Label>
                  <Select
                    value={newBooking.booking_type}
                    onValueChange={(value: "passenger" | "goods") =>
                      setNewBooking({ ...newBooking, booking_type: value })
                    }
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="passenger">Passenger Transport</SelectItem>
                      <SelectItem value="goods">Goods Transport</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div>
                  <Label htmlFor="pickup_location">Pickup Location</Label>
                  <Input
                    id="pickup_location"
                    value={newBooking.pickup_location}
                    onChange={(e) =>
                      setNewBooking({ ...newBooking, pickup_location: e.target.value })
                    }
                    placeholder="Enter pickup location"
                    required
                  />
                </div>

                <div>
                  <Label htmlFor="delivery_location">Delivery Location</Label>
                  <Input
                    id="delivery_location"
                    value={newBooking.delivery_location}
                    onChange={(e) =>
                      setNewBooking({ ...newBooking, delivery_location: e.target.value })
                    }
                    placeholder="Enter delivery location"
                    required
                  />
                </div>

                {newBooking.booking_type === "passenger" && (
                  <div>
                    <Label htmlFor="passenger_count">Number of Passengers</Label>
                    <Input
                      id="passenger_count"
                      type="number"
                      min="1"
                      value={newBooking.passenger_count}
                      onChange={(e) =>
                        setNewBooking({
                          ...newBooking,
                          passenger_count: parseInt(e.target.value),
                        })
                      }
                    />
                  </div>
                )}

                {newBooking.booking_type === "goods" && (
                  <div>
                    <Label htmlFor="goods_type">Goods Type</Label>
                    <Select
                      value={newBooking.goods_type}
                      onValueChange={(value: string) =>
                        setNewBooking({ ...newBooking, goods_type: value })
                      }
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select goods type" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="parcel">Parcel</SelectItem>
                        <SelectItem value="bulk">Bulk</SelectItem>
                        <SelectItem value="corporate">Corporate</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                )}

                <div>
                  <Label htmlFor="special_instructions">Special Instructions</Label>
                  <Textarea
                    id="special_instructions"
                    value={newBooking.special_instructions}
                    onChange={(e) =>
                      setNewBooking({ ...newBooking, special_instructions: e.target.value })
                    }
                    placeholder="Any special requests or notes"
                  />
                </div>

                <Button type="submit" className="w-full">
                  Create Booking
                </Button>
              </form>
            </CardContent>
          </Card>

          {/* Bookings List */}
          <Card>
            <CardHeader>
              <CardTitle>Recent Bookings</CardTitle>
              <CardDescription>Manage and assign bookings</CardDescription>
            </CardHeader>
            <CardContent>
              {dataLoading ? (
                <div className="text-center py-8">Loading...</div>
              ) : bookings.length === 0 ? (
                <div className="text-center py-8 text-muted-foreground">No bookings yet</div>
              ) : (
                <div className="space-y-4 max-h-[600px] overflow-y-auto">
                  {bookings.map((booking) => (
                    <Card key={booking.id}>
                      <CardContent className="pt-6 space-y-3">
                        <div className="flex justify-between items-start">
                          <div>
                            <p className="font-semibold">{booking.tracking_id}</p>
                            <p className="text-sm text-muted-foreground">
                              {booking.booking_type === "passenger" ? "Passenger" : "Goods"}
                            </p>
                          </div>
                          <span
                            className={`px-2 py-1 rounded text-xs ${booking.status === "pending"
                              ? "bg-yellow-100 text-yellow-800"
                              : booking.status === "assigned"
                                ? "bg-blue-100 text-blue-800"
                                : booking.status === "in_transit"
                                  ? "bg-purple-100 text-purple-800"
                                  : "bg-green-100 text-green-800"
                              }`}
                          >
                            {booking.status}
                          </span>
                        </div>

                        <div className="text-sm space-y-1">
                          <div className="flex items-start gap-2">
                            <MapPin className="h-4 w-4 text-muted-foreground mt-0.5 flex-shrink-0" />
                            <div>
                              <p className="font-medium">From: {booking.pickup_location}</p>
                              <p className="text-muted-foreground">To: {booking.delivery_location}</p>
                            </div>
                          </div>
                        </div>

                        {!booking.driver_id && (
                          <div className="space-y-2">
                            <Label className="text-xs">Assign Driver & Vehicle</Label>
                            <div className="flex gap-2">
                              <Select
                                onValueChange={(driverId) => {
                                  const vehicle = vehicles.find((v) => v.driver_id === driverId);
                                  if (vehicle) {
                                    handleAssignDriver(booking.id, driverId, vehicle.id);
                                  }
                                }}
                              >
                                <SelectTrigger className="text-xs">
                                  <SelectValue placeholder="Select driver" />
                                </SelectTrigger>
                                <SelectContent>
                                  {drivers.map((driver) => (
                                    <SelectItem key={driver.id} value={driver.id}>
                                      {driver.full_name}
                                    </SelectItem>
                                  ))}
                                </SelectContent>
                              </Select>
                            </div>
                          </div>
                        )}

                        <div className="space-y-2">
                          <Label className="text-xs">Update Status</Label>
                          <Select
                            value={booking.status}
                            onValueChange={(status: string) => handleUpdateStatus(booking.id, status)}
                          >
                            <SelectTrigger className="text-xs">
                              <SelectValue />
                            </SelectTrigger>
                            <SelectContent>
                              <SelectItem value="pending">Pending</SelectItem>
                              <SelectItem value="dispatched">Dispatched</SelectItem>
                              <SelectItem value="delivered">Delivered</SelectItem>
                              <SelectItem value="received">Received</SelectItem>
                            </SelectContent>
                          </Select>
                        </div>
                      </CardContent>
                    </Card>
                  ))}
                </div>
              )}
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
};

export default AssistantDashboard;
