import { useState, useEffect } from "react";
import { useNavigate, Link } from "react-router-dom";
import Header from "@/components/layout/Header";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { MapPin, Users, Package, Clock, ArrowRight, Shield, Zap, Info, Loader2 } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { useToast } from "@/hooks/use-toast";
import MapInput from "@/components/MapInput";

const Booking = () => {
  const navigate = useNavigate();
  const { profile, user } = useAuth();
  const { toast } = useToast();
  const [loading, setLoading] = useState(false);
  const [mapboxToken, setMapboxToken] = useState("");

  const [formData, setFormData] = useState({
    bookingType: "",
    pickupLocation: "",
    pickupLat: undefined as number | undefined,
    pickupLng: undefined as number | undefined,
    deliveryLocation: "",
    deliveryLat: undefined as number | undefined,
    deliveryLng: undefined as number | undefined,
    passengerCount: "",
    goodsType: "",
    specialInstructions: "",
  });

  useEffect(() => {
    const fetchToken = async () => {
      // Priority 1: Environment Variable
      const envToken = import.meta.env.VITE_MAPBOX_ACCESS_TOKEN;
      if (envToken) {
        setMapboxToken(envToken);
        return;
      }

      // Priority 2: Supabase Edge Function fallback
      const { data } = await supabase.functions.invoke('get-mapbox-token');
      if (data?.token) {
        setMapboxToken(data.token);
      }
    };
    fetchToken();
  }, []);

  const handleInputChange = (field: string, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!profile || !user) {
      toast({
        title: "Access Restricted",
        description: "Please enter the base via authentication to initialize a booking.",
        variant: "destructive",
      });
      navigate("/auth");
      return;
    }

    setLoading(true);
    try {
      const bookingData = {
        customer_id: profile.id,
        booking_type: formData.bookingType as 'passenger' | 'goods',
        pickup_location: formData.pickupLocation,
        pickup_latitude: formData.pickupLat,
        pickup_longitude: formData.pickupLng,
        delivery_location: formData.deliveryLocation,
        delivery_latitude: formData.deliveryLat,
        delivery_longitude: formData.deliveryLng,
        passenger_count: formData.bookingType === 'passenger' ? parseInt(formData.passengerCount) || null : null,
        goods_type: formData.bookingType === 'goods' ? (formData.goodsType as 'parcel' | 'bulk' | 'corporate') : null,
        special_instructions: formData.specialInstructions || null,
        tracking_id: '', // Will be auto-generated by trigger
      };

      const { data, error } = await supabase
        .from('bookings')
        .insert(bookingData)
        .select()
        .single();

      if (error) throw error;

      toast({
        title: "Deployment Successful",
        description: `Your unique tracking signature is: ${data.tracking_id}`,
      });

      // Reset form
      setFormData({
        bookingType: "",
        pickupLocation: "",
        pickupLat: undefined,
        pickupLng: undefined,
        deliveryLocation: "",
        deliveryLat: undefined,
        deliveryLng: undefined,
        passengerCount: "",
        goodsType: "",
        specialInstructions: "",
      });

    } catch (error: any) {
      toast({
        title: "Initialization Failed",
        description: error.message,
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  if (!user) {
    return (
      <div className="min-h-screen grain flex items-center justify-center p-6 bg-black">
        <Card className="w-full max-w-md glass-card border-none p-4 text-center">
          <CardHeader>
            <Shield className="h-16 w-16 text-primary mx-auto mb-6 opacity-80" />
            <CardTitle className="text-3xl font-black text-white tracking-tighter uppercase">Authorized Entry Only</CardTitle>
            <CardDescription className="text-slate-400 font-light mt-2">Initialize your credentials to access the SafeCargo booking protocol.</CardDescription>
          </CardHeader>
          <CardContent className="pt-6">
            <Button onClick={() => navigate("/auth")} className="w-full h-14 btn-cyan text-sm font-black uppercase tracking-widest">
              Establish Session
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-screen grain overflow-hidden">
      <Header />

      <main className="relative pt-24 pb-20 px-6">
        {/* Background Accents */}
        <div className="absolute top-[15%] left-[-10%] w-[40%] h-[40%] bg-primary/10 rounded-full blur-[120px]" />

        <div className="container mx-auto max-w-4xl relative z-10">
          <div className="text-center mb-16">
            <h1 className="text-4xl md:text-6xl font-black tracking-tighter mb-4 hero-text-glow uppercase">Mission <span className="text-primary italic">Initialization</span></h1>
            <p className="text-slate-400 max-w-2xl mx-auto font-light">Specify coordinates and parameters for your SafeCargo deployment.</p>
          </div>

          <Card className="glass-card border-none p-6">
            <CardHeader className="pb-8">
              <CardTitle className="flex items-center gap-3 text-white uppercase font-black tracking-tight">
                <Zap className="h-6 w-6 text-primary" />
                Deployment Config
              </CardTitle>
              <CardDescription className="text-slate-400">All fields are monitored for real-time logistical adjustment.</CardDescription>
            </CardHeader>
            <CardContent>
              <form onSubmit={handleSubmit} className="space-y-8">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                  <div className="space-y-3">
                    <Label htmlFor="bookingType" className="text-[10px] font-black text-slate-500 uppercase tracking-widest ml-1">Operational Class</Label>
                    <Select
                      value={formData.bookingType}
                      onValueChange={(value) => handleInputChange("bookingType", value)}
                    >
                      <SelectTrigger className="h-12 bg-white/5 border-white/10 text-white rounded-xl focus:ring-primary/40">
                        <SelectValue placeholder="Selection Required" />
                      </SelectTrigger>
                      <SelectContent className="bg-slate-900 border-white/10 text-white rounded-xl">
                        <SelectItem value="passenger" className="focus:bg-primary/20">
                          <div className="flex items-center gap-2">
                            <Users className="h-4 w-4 text-primary" />
                            Personnel Transport
                          </div>
                        </SelectItem>
                        <SelectItem value="goods" className="focus:bg-primary/20">
                          <div className="flex items-center gap-2">
                            <Package className="h-4 w-4 text-primary" />
                            Asset Relocation
                          </div>
                        </SelectItem>
                      </SelectContent>
                    </Select>
                  </div>

                  {formData.bookingType === "passenger" && (
                    <div className="space-y-3">
                      <Label htmlFor="passengerCount" className="text-[10px] font-black text-slate-500 uppercase tracking-widest ml-1">Head Count</Label>
                      <div className="relative">
                        <Users className="absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-500" />
                        <Input
                          id="passengerCount"
                          type="number"
                          min="1"
                          max="50"
                          value={formData.passengerCount}
                          onChange={(e) => handleInputChange("passengerCount", e.target.value)}
                          placeholder="Capacity"
                          className="h-12 bg-white/5 border-white/10 text-white placeholder:text-slate-700 pl-11 rounded-xl focus-visible:ring-primary/40"
                        />
                      </div>
                    </div>
                  )}

                  {formData.bookingType === "goods" && (
                    <div className="space-y-3">
                      <Label htmlFor="goodsType" className="text-[10px] font-black text-slate-500 uppercase tracking-widest ml-1">Asset Category</Label>
                      <Select
                        value={formData.goodsType}
                        onValueChange={(value) => handleInputChange("goodsType", value)}
                      >
                        <SelectTrigger className="h-12 bg-white/5 border-white/10 text-white rounded-xl focus:ring-primary/40">
                          <SelectValue placeholder="Classification" />
                        </SelectTrigger>
                        <SelectContent className="bg-slate-900 border-white/10 text-white rounded-xl">
                          <SelectItem value="parcel" className="focus:bg-primary/20">Standard Parcel</SelectItem>
                          <SelectItem value="bulk" className="focus:bg-primary/20">High-Volume Bulk</SelectItem>
                          <SelectItem value="corporate" className="focus:bg-primary/20">Corporate Assets</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                  )}
                </div>

                <div className="space-y-6">
                  {mapboxToken ? (
                    <>
                      <div className="space-y-4">
                        <Label className="text-[10px] font-black text-slate-500 uppercase tracking-widest ml-1">Point of Origin</Label>
                        <div className="p-1 rounded-2xl bg-white/5 border border-white/5 overflow-hidden">
                          <MapInput
                            label=""
                            value={formData.pickupLocation}
                            onChange={(value, lat, lng) => {
                              setFormData(prev => ({
                                ...prev,
                                pickupLocation: value,
                                pickupLat: lat,
                                pickupLng: lng,
                              }));
                            }}
                            apiKey={mapboxToken}
                            placeholder="Initialize pickup coordinates"
                          />
                        </div>
                      </div>

                      <div className="space-y-4">
                        <Label className="text-[10px] font-black text-slate-500 uppercase tracking-widest ml-1">Target Coordinates</Label>
                        <div className="p-1 rounded-2xl bg-white/5 border border-white/5 overflow-hidden">
                          <MapInput
                            label=""
                            value={formData.deliveryLocation}
                            onChange={(value, lat, lng) => {
                              setFormData(prev => ({
                                ...prev,
                                deliveryLocation: value,
                                deliveryLat: lat,
                                deliveryLng: lng,
                              }));
                            }}
                            apiKey={mapboxToken}
                            placeholder="Specify destination markers"
                          />
                        </div>
                      </div>
                    </>
                  ) : (
                    <div className="flex items-center gap-3 p-4 rounded-xl bg-primary/5 border border-primary/20">
                      <Loader2 className="h-5 w-5 text-primary animate-spin" />
                      <p className="text-sm font-bold text-slate-400 uppercase tracking-widest">Synchronizing orbital map services...</p>
                    </div>
                  )}
                </div>

                <div className="space-y-3">
                  <Label htmlFor="specialInstructions" className="text-[10px] font-black text-slate-500 uppercase tracking-widest ml-1">Mission Constraints (Optional)</Label>
                  <div className="relative">
                    <Info className="absolute left-4 top-4 h-4 w-4 text-slate-500" />
                    <Textarea
                      id="specialInstructions"
                      value={formData.specialInstructions}
                      onChange={(e) => handleInputChange("specialInstructions", e.target.value)}
                      placeholder="Specify unique parameters, environmental risks, or timing constraints..."
                      rows={4}
                      className="bg-white/5 border-white/10 text-white placeholder:text-slate-700 rounded-2xl focus-visible:ring-primary/40 pt-3.5 pl-11"
                    />
                  </div>
                </div>

                <div className="flex flex-col sm:flex-row gap-6 pt-4">
                  <Button
                    type="button"
                    variant="outline"
                    onClick={() => navigate("/")}
                    className="flex-1 h-14 border-white/10 hover:bg-white/5 text-slate-400 uppercase tracking-widest font-black text-xs"
                  >
                    Abort Commission
                  </Button>
                  <Button
                    type="submit"
                    disabled={!formData.bookingType || !formData.pickupLocation || !formData.deliveryLocation || loading}
                    className="flex-1 h-14 btn-cyan text-sm font-black uppercase tracking-widest group"
                  >
                    {loading ? (
                      <Loader2 className="h-5 w-5 animate-spin" />
                    ) : (
                      <>Initialize Deployment <ArrowRight className="ml-2 h-4 w-4 group-hover:translate-x-1 transition-transform" /></>
                    )}
                  </Button>
                </div>
              </form>
            </CardContent>
          </Card>
        </div>
      </main>

      <footer className="py-12 border-t border-white/5 bg-black/50 text-center relative z-10">
        <p className="text-slate-500 text-sm tracking-widest uppercase">
          © 2026 SafeCargo Transporters. Precision Logistics Protocol.
        </p>
      </footer>
    </div>
  );
};

export default Booking;